### ISSUE TITLE
任务创建以后没有正常执行，无任何执行记录

### ISSUE THREAD

**Issue by muye100110** [labulakalia/crocodile#110]
任务创建以后，到时间没有执行，找不到执行记录，日志等都是空的
![image](https://user-images.githubusercontent.com/31815119/230266624-83e6dcd9-b954-4d5a-abd8-60f13e281d4d.png)
![image](https://user-images.githubusercontent.com/31815119/230266776-7f3a66a9-8ace-4e32-bcfa-def92eac48e2.png)
![image](https://user-images.githubusercontent.com/31815119/230266947-5427f634-889e-41e6-af5c-2379c710c071.png)

**Comment by Nuoky** [comment]
同，解决了么@muye100110

**Comment by muye100110** [comment]
没解决，后来没去看



在 2023-04-23 21:28:15，"Nuoky" ***@***.***> 写道：

***@***.***

**Comment by Nuoky** [comment]
可能是无法访问到master之类的问题？按下面配置下暂时解决问题

1. core_docker.toml 把 serveraddrs 改成了宿主机内网IP
```
serveraddrs = ["172..x.x.x:8080"]
```
2. docker-compose.yml 改成了networks bridge
```
version: '3.1'

networks:
  app-crocodile:
    driver: bridge

services: 
    master: 
        image: labulaka522/crocodile
        container_name: crocodile_master
        restart: always
        ports: 
          - 8080:8080
        volumes: 
          - $PWD/core_docker.toml:/app/core.toml
        networks:
          - app-crocodile
    worker:       
        image: labulaka522/crocodile:worker
        container_name: crocodile_worker
        ports: 
          - 8088:8088
        volumes: 
            - $PWD/core_docker.toml:/app/core.toml
        networks:
          - app-crocodile
    mysql:
        image: mysql:latest
        environment:
          - TZ=Asia/Shanghai
          - MYSQL_ROOT_PASSWORD=crocodile # set the root password
          - MYSQL_DATABASE=crocodile
        volumes: 
           - "./data:/var/lib/mysql"   # mysql数据持久化
        ports: 
          - 3306:3306
        networks:
          - app-crocodile
    redis:
        image: redis:latest
        restart: always
        ports: 
          - 6379:6379
        networks:
            - app-crocodile
```
